// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM1fOmMNP0eTd0sz9h7U4FLaec6r8CvFs',
    appId: '1:971246870084:web:484936354ad3487095e611',
    messagingSenderId: '971246870084',
    projectId: 'testttapp-5d4ccb19',
    authDomain: 'testttapp-5d4ccb19.firebaseapp.com',
    storageBucket: 'testttapp-5d4ccb19.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXE4RCesGxNKcMRqpY4W4Hsfeeay2co7k',
    appId: '1:971246870084:android:1b8395c80d06f9a295e611',
    messagingSenderId: '971246870084',
    projectId: 'testttapp-5d4ccb19',
    storageBucket: 'testttapp-5d4ccb19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqwARXmLPY5XP0GzySRFA3-Ep-TXhB34w',
    appId: '1:971246870084:ios:aaae1f2524c9394f95e611',
    messagingSenderId: '971246870084',
    projectId: 'testttapp-5d4ccb19',
    storageBucket: 'testttapp-5d4ccb19.firebasestorage.app',
    iosBundleId: 'com.example.threeBodyProblem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqwARXmLPY5XP0GzySRFA3-Ep-TXhB34w',
    appId: '1:971246870084:ios:aaae1f2524c9394f95e611',
    messagingSenderId: '971246870084',
    projectId: 'testttapp-5d4ccb19',
    storageBucket: 'testttapp-5d4ccb19.firebasestorage.app',
    iosBundleId: 'com.example.threeBodyProblem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM1fOmMNP0eTd0sz9h7U4FLaec6r8CvFs',
    appId: '1:971246870084:web:30ce028723c279ea95e611',
    messagingSenderId: '971246870084',
    projectId: 'testttapp-5d4ccb19',
    authDomain: 'testttapp-5d4ccb19.firebaseapp.com',
    storageBucket: 'testttapp-5d4ccb19.firebasestorage.app',
  );
}
